AWSTemplateFormatVersion: '2010-09-09'
Description: 'Elastic Beanstalk Environment for CMIS Store'

Resources:
  EBServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'cmi-eb-service-role'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [elasticbeanstalk.amazonaws.com]
          Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService

  EBInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'cmi-eb-ec2-role'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  EBInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: 'cmi-eb-ec2-role'
      Roles:
        - !Ref EBInstanceRole

  EBApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: 'cmibattery-production'
      Description: 'CMI Battery E-commerce Application'

  EBEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref EBApplication
      EnvironmentName: 'cmibattery-prod-env'
      SolutionStackName: '64bit Amazon Linux 2023 v4.13.7 running Docker'
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref EBInstanceProfile
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t3.small
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: !Ref EBServiceRole

Outputs:
  EnvironmentURL:
    Description: 'URL of the Elastic Beanstalk Environment'
    Value: !GetAtt EBEnvironment.EndpointURL
